variables:
  TERRAFORM_IMAGE: "iits/vault-kubectl-terraform:0.14.8-makefix"
stages:
  - plan
  - apply

plan-dev:
  stage: plan
  image: $TERRAFORM_IMAGE
  variables:
    OTC_CLOUD_NAME: showcase
  script:
    - cd terraform-playground/showcase
    - terraform init
    - terraform plan | sed -e 's/".\{32\}"/"__REDACTED__"/g' -e "s/'.\{32\}'/'__REDACTED__'/g"


apply-dev:
  stage: apply
  image: $TERRAFORM_IMAGE
  when: manual
  variables:
    OTC_CLOUD_NAME: showcase
  script:
    - cd terraform-playground/showcase
    - terraform init
    - terraform apply -auto-approve | sed -e 's/".\{32\}"/"__REDACTED__"/g' -e "s/'.\{32\}'/'__REDACTED__'/g"

before_script:
  - export VAULT_ADDR="REPLACE_ME"
  - export VAULT_TOKEN=$(vault write -field=token auth/gitlab/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID) || true
  - export ACCESS_KEY=$(vault kv get --field access_key secret/otc_credentials/$OTC_CLOUD_NAME)
  - export SECRET_KEY=$(vault kv get --field secret_key secret/otc_credentials/$OTC_CLOUD_NAME)
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY